### ISSUE TITLE
Sorry, my ignoramus questions about the Waterlily again

### ISSUE THREAD

**Issue by tiinaroose** [WaterLily-jl/WaterLily.jl#126]
In the moving sphere demo TwoD_cylinder_VIV.jl
there are lines:
# initial condition FSI
    p0=radius/3; v0=0; a0=0; t0=0

    # motion function uses global var to adjust
    posx(t) = p0 + (t-t0)*v0

    # motion definition
    map(x,t) = x - SA[0,posx(t)]

Why does this imply any movement? v0=0? I've made the ellipse move up and down just like the sphere, but I want to make it now rotate. However, I do not understand how the up and down movement is implemented in the first place in WaterLily.

**Comment by marinlauber** [comment]
@abdurrehman92 I'll see if I can find it
