### ISSUE TITLE
support for nonunifrom grids

### ISSUE THREAD

**Issue by biao-geng-me** [WaterLily-jl/WaterLily.jl#170]
I read in the paper that WaterLily uses uniform grids. While this is straightforward to setup, it limits the size of the flow domain. The grids are commonly stretched in Cartesian grid + Immersed boundary method type of CFD code.

**Comment by biaogeng** [comment]
I just wanted to follow up with this issue. Could you please share some insights on the choice of uniform grids in WaterLily? Any comments on implementing nonuniform grids in WaterLily? Thank you!

**Comment by biao-geng-me** [comment]
Just to follow up with the issue. Could you share some insights on the choice of uniform grids in WaterLily? Any comment on implementing nonuniform grids in WaterLily? Thank you!

**Comment by b-fg** [comment]
There is some work in progress for reducing flow domains using Biot Savart boundary conditions: [BiotSavartBCs.jl](https://github.com/weymouth/BiotSavartBCs.jl), [arXiv](https://arxiv.org/abs/2404.09034). There is not short-term plan for non-uniform grids, but PRs are welcomed!

**Comment by biao-geng-me** [comment]
Thank you for the information. I did some test cases using the BiotSavartBCs.jl. It seems that its performance is not good. The `biot_mom_step!` function was from 10 to 100 times slower than the regular `mom_step!` function. In the end there was little speedup compared to using regular B.C.s and a large domain.

I'm considering working on adding non-uniform grids in WaterLily, but while I have some experience with CFD algorithms, Julia is totally new to me. How much effort do you think it will be to add support for non-uniform grids in WaterLily?

**Comment by weymouth** [comment]
I don't think we plan to go to non-uniform grids in WaterLily. Part of the appeal is the simplicity. I would be open to an extension package with this capability, but not in this repo. 

Also, we just completed a huge speed up of the [BiotSavartBCs](https://github.com/weymouth/BiotSavartBCs.jl/tree/refactor3D). The speed is now very similar to the master repo. Maybe check that out.
