### ISSUE TITLE
force coefficients are half the correct values

### ISSUE THREAD

**Issue by biao-geng-me** [WaterLily-jl/WaterLily.jl#173]
First, thank you and congratulations on this amazing work! As someone who's been working with CFD on HPC using CPUs, the speed of WaterLily using GPUs is just jaw-dropping.

We are trying to incorprate WaterLily in our workflow. So far we've tested a circular cylinder case and a square cylinder case, both 3D. The circular case had accurate force coefficient compared to literature. However, when switched to the square shape, I had roughly *half* the correct force coefficients ([reference](https://onlinelibrary.wiley.com/doi/full/10.1002/fld.2416)). For example, the mean drag @ Re=100 is about 1.5, but I got ~0.75 from WaterLily. I calculated the coefficient using the built-in metrics function `total_force`

```julia
    force = WaterLily.total_force(sim)
    force./=(0.5sim.L*nz*sim.U^2) # scale the forces! nz is the dimension in the z axis
```

Confoundingly, this part was not changed when switching from circular to square cylinder.

I inspected the pressure field (shown below) at one time instant, and it looked correct and compared well with the pressure field using another CFD code.

![image](https://github.com/user-attachments/assets/4625a1e5-4223-43ef-9a49-a91f2c2a1044)

The drag force coefficient history is
![drag](https://github.com/user-attachments/assets/74496732-7ccd-44ac-8962-dbbe3837da25)

My code for this case is attached if it helps. Thank you for your time!
[square_cylinder_3D.zip](https://github.com/user-attachments/files/17495883/square_cylinder_3D.zip)

**Comment by marinlauber** [comment]
Hi @biao-geng-me, 

This seems wired as the pressure field looks ok. What does `nz` represents? Looking at your script it seems it is the spanwise dimension of your domain, which cannot be used as the reference lengthscale (if you have a 3D cube and not square cylinder).

Marin

**Comment by weymouth** [comment]
Apologies, I was teaching in the last quarter, so I'm just catching up with some of these issues. Did you figure this out?

**Comment by biao-geng-me** [comment]
@weymouth @marinlauber Thank you for the responses. No, we didn't figure it out. We decided to proceed with the project using WaterLily nontheless, since the flow field looked correct and we don't need the forces at the moment. It'll be great if you could take the time to look into this case. I lowkey hope it's not some dumb/simple mistaken in my setup, but my apologies if that's the case.

@marinlauber `nz` indeed is the spanwise dimension of the cylinder. I've double checked that the shape is indeed a square cylinder (not a cube). The spanwise dimension passes through the whole domain in the z direction.

Thank you again for your work and your input!

**Comment by weymouth** [comment]
I certainly _hope_ this is just a simple mistake in the setup ;-) 

As @Marin mentioned, the pressure outside the box looks perfect, and you're off by a factor of two. It's _probably_ a bug in the input or output scaling. 

1. Are you sure that `sim.L` is the same width used in the literature to scale the forces? From you picture, the full width looks to be around 50 cells...
2. Are you sure you've matched your reference Re correctly? 50 cells is fairly low, so hopefully you're trying to match a low Re case. 
3. One good way to catch scaling issues is to play around with the geometry and resolution. How does this change with refinement, or when you adjust the span to width ratiio?

**Comment by weymouth** [comment]
Here is a very minimal working example:

```julia
using WaterLily,StaticArrays,TypedTables,Plots
function make_square(N::NTuple{n,Int};H=N[2]÷8,Re=200) where n
  U = ntuple(i->i==1 ? 1 : 0,n)       # n-dimensional flow
  function sdf(x,t)
    y = abs.(SA[x[1],x[2]] .- N[2]÷2) # positive quadrant vector from the center
    √sum(abs2,y-min.(y,H))             # using half-width to define shape from center
  end
  Simulation(N,U,2H;body=AutoBody(sdf),ν=2H/Re) # use full-width for scaling
end

sim = make_square((256,128)); # 2D
hist = map(100:0.1:110) do t
  sim_step!(sim,t,remeasure=false,verbose=true)
  f = WaterLily.total_force(sim)/(0.5sim.L*sim.U^2)
  (t=t,drag=-f[1],lift=f[2])
end |> Table
plot(hist.t,hist.drag,label="drag")
plot!(hist.t,hist.lift,label="lift")
plot!(ylabel="F/½ρU²H",xlabel="tU/H",
  title="2D square forces at Re=UH/ν=200")
```
![square](https://github.com/user-attachments/assets/4d411e72-4fb6-4cfb-92ca-409b05a0a855)

```julia
N = (256,128,64); sim = make_square(N); A = sim.L*N[3]
hist = map(100:0.1:110) do t
  sim_step!(sim,t,remeasure=false,verbose=true)
  f = WaterLily.total_force(sim)/(0.5A*sim.U^2)
  (t=t,drag=-f[1],lift=f[2])
end |> Table
```
(waiting on result...)

Obviously, this is low resolution and low Re, but the forces seem to have the right magnitude. Is this helpful?

**Comment by weymouth** [comment]
Here's the 3D version at Re=2000
![square_prism](https://github.com/user-attachments/assets/4b6bca38-c5dc-44fd-aa84-9d3c963e3c8a)
