### ISSUE TITLE
simulation pause and continue

### ISSUE THREAD

**Issue by ngmay12138** [WaterLily-jl/WaterLily.jl#176]
Hello,
I would like to ask if there is a way to make the simulation pause and continue to run. For example, if I set the t  to 2,like sim_step!(sim,2), and after 1(sim_time)  stop the program, can I start with the 1(sim_time)  and continue with the next 1~2(sim_time)? 
Thanks

**Comment by b-fg** [comment]
Our VTK i/o features supports this. Please take a look at this example:
https://github.com/WaterLily-jl/WaterLily-Examples/blob/main/examples/ThreeD_CylinderVTKRestart.jl

I wouldn't do `sim_step!(sim,T)`, but instead a loop where you save a restart file every `dt` time units: 
```julia
T = 2 # non-dimensional simulation time
dt = 0.2 # non-dimensional simulation time interval
for i in range(1,Int(T/dt))
    sim_step!(sim, sim_time(sim)+i*dt)
    # ... write `sim` in VTK file, see example
end
```
So if the program stops for some reason, you will have a restart file available.

**Comment by ngmay12138** [comment]
Thank you
